#!/bin/bash

#создает виртуальную сеть для контейнеров docker и присоединяет ее к локальному
#мосту - контейнеры из этой сети будут видны в локалке!!!

. ./defaults

NET_NAME=$N_NAME
IFACE=$IFACE
GW=$GW
HOST=$HOST

echo "${NET_NAME}:$NET on ${IFACE} connect via ${NET_IFACE} Host=${HOST} gateway=${GW}"

exit

#интерфейс для связи с хостом
ifconfig ${IFACE}-nds down
ip link delete ${IFACE}-nds
ip link add ${IFACE}-nds link ${IFACE} type macvlan mode bridge
ifconfig ${IFACE}-nds $HOST
#выход в интернет для контейнеров
#iptables -t nat -D POSTROUTING -s ${NET}.0/24 ! -d ${NET}.0/24 -j MASQUERADE
#iptables -t nat -A POSTROUTING -s ${NET}.0/24 ! -d ${NET}.0/24 -j MASQUERADE

#создадим внутерннюю сеть
docker network rm ${NET_NAME}
docker network create --driver=macvlan \
                      --subnet=${NET}.0/24 \
                      --ip-range=${NET}.240/28 \
                      -o macvlan_mode=bridge \
                      -o parent=${IFACE} \
                      --gateway=$GW \
                      ${NET_NAME}

#необходимо, что бы работала связь с хостом и выход в интернет.
#нужно сделать для каждого контейнера
ip route add 192.168.0.241 dev br0-nds
ip route add 192.168.0.242 dev br0-nds

#удалим ненужный интерфейс
ifconfig docker0 down
brctl delbr docker0
